language: node_js
sudo: false
addons:
node_js:
- '6'
cache:
  directories:
  - node_modules
script:
- npm run lint
- istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec --recursive
